# Generated by Django 2.2.5 on 2020-09-15 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caminhoes', '0001_initial'),
        ('motoristas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mtr',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False, verbose_name='Numero')),
                ('alias', models.CharField(max_length=155, verbose_name='alias')),
                ('saida', models.DateTimeField(blank=True, null=True, verbose_name='Data e hora da saida')),
                ('chegada', models.DateTimeField(blank=True, null=True, verbose_name='Data e hora da chegada')),
                ('caminhao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caminhoes.Caminhoes')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motoristas.Motoristas')),
            ],
        ),
    ]
