# Generated by Django 2.2.5 on 2020-09-15 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_multidev', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Multidev')),
                ('razao_social', models.CharField(max_length=115, verbose_name='Razão Social')),
                ('fantasia', models.CharField(max_length=115, verbose_name='Nome Fantasia')),
                ('logradouro', models.CharField(blank=True, max_length=115, null=True, verbose_name='Logradouro')),
                ('bairro', models.CharField(blank=True, max_length=115, null=True, verbose_name='Bairro')),
                ('municipio', models.CharField(blank=True, max_length=115, null=True, verbose_name='Municipio')),
                ('estado', models.CharField(blank=True, max_length=115, null=True, verbose_name='Estado')),
                ('latitude', models.CharField(max_length=100, verbose_name='Latitude')),
                ('longitude', models.CharField(max_length=100, verbose_name='Longitude')),
                ('gestao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
