# Generated by Django 2.2.5 on 2020-08-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_auto_20200817_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id_multidev',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Multidev'),
        ),
    ]
