# Generated by Django 2.2.5 on 2020-09-15 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('mtr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=155, verbose_name='Rua')),
                ('numero', models.IntegerField(verbose_name='Numero')),
                ('bairro', models.CharField(max_length=155, verbose_name='Bairro')),
                ('municipio', models.CharField(max_length=155, verbose_name='Municipio')),
                ('estado', models.CharField(max_length=155, verbose_name='Estado')),
                ('lat', models.CharField(max_length=20, verbose_name='Latitude')),
                ('long', models.CharField(max_length=20, verbose_name='Longitude')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
                ('mtr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtr.Mtr')),
            ],
        ),
    ]
