# Generated by Django 2.2.5 on 2020-08-06 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencia',
            name='lat',
            field=models.CharField(default=1, max_length=20, verbose_name='Latitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sequencia',
            name='long',
            field=models.CharField(default=1, max_length=20, verbose_name='Longitude'),
            preserve_default=False,
        ),
    ]
