# Generated by Django 2.2.5 on 2020-09-15 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Motoristas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_multidev', models.IntegerField(verbose_name='Id Multidev')),
                ('nome', models.CharField(max_length=115, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('mopp', models.CharField(blank=True, max_length=20, null=True, verbose_name='MOPP')),
                ('mopp_validade', models.DateField(blank=True, null=True, verbose_name='Validade MOPP')),
                ('cnh', models.CharField(max_length=20, verbose_name='CNH')),
                ('cnh_categoria', models.CharField(max_length=2, verbose_name='Categoria Cnh')),
                ('cnh_validade', models.DateField(verbose_name='Validade CNH')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
