# Generated by Django 2.2.5 on 2020-09-15 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('motoristas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=155, verbose_name='Latitude')),
                ('lng', models.CharField(max_length=155, verbose_name='Longitude')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motoristas.Motoristas')),
            ],
        ),
    ]
